resources:
- name: every-10m
  type: time
  source: {interval: 10m}

jobs:
- name: annoy
  plan:
  - get: every-10m
    trigger: true
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hey! Listen!"]
