---
resources:
  - name: concourse-examples
    type: git
    source:
      uri: git@github.com:jkamenik/concourse-examples.git
      branch: master
      private_key: {{git_private_key}}

jobs:
  - name: run-uname
    public: true
    plan:
      - get: concourse-examples
        trigger: true  # this allows plan to be triggered if concourse-examples changes
      - task: uname
        file: concourse-examples/tasks/uname.yml
